ci: no longer test sharedb against node v14 (#3881)
- seems no longer compatible as of v4.1.2
- https://github.com/share/sharedb/commit/06cc3877fd9b53d1ddc3ecdd3df11f68fbdbb100\#diff-3fb720f70ea34fb2975fd6c38ac4b6b6131373be2abfa4760dfaae8a25daaee2R11
- Uncaught TypeError: util.hasOwn is not a function